### ISSUE TITLE
apache_up gauge doesn't reset to 0 when both apache and exporter are compose services

### ISSUE THREAD

**Issue by MrRothstein** [Lusitaniae/apache_exporter#68]
I'm running apache_exporter and apache httpd as separate services defined in a single docker-compose.yml:

```
  httpd:
    image: custom/httpd:2.4
    container_name: httpd
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - some-network

  apache-exporter:
    image: custom/apache_exporter
    container_name: apache-exporter
    entrypoint: '/bin/apache_exporter -scrape_uri "http://httpd/server-status/?auto"'
    ports:
      - 9117:9117
    restart: unless-stopped
    depends_on:
      - httpd
    networks:
      - some-network
```

Everything runs as expected immediately after:

`
docker-compose up -d
`

However, after 
`docker-compose stop httpd`

the following metrics are still being reported:

apache_cpuload 0.00441176
apache_exporter_build_info{branch="master",goversion="go1.8.7",revision="6195241a96c02af175ba2842dfd883682133b066",version="0.7.0"} 1
apache_up 1
apache_workers{state="busy"} 1
apache_workers{state="idle"} 74

The values remain the same with every refresh.

I'm guessing this is happening because the NewRequest call is resulting in error which terminates collection before the up gauge can be set to 0, but i'm not sure where to look for the error message. 

`docker logs apache-exporter`

does not appear to capture the error.
